- hosts: all
  become: true
  tasks:
    # Actualizamos el sistema
    - name: Actualizamos el sistema
      apt:
        update_cache: yes
        upgrade: dist

    # Instalar apache2 y git
    - name: "Instalar git y apache2"
      ansible.builtin.apt:
        name:
          - git
          - apache2
        state: present

    # Copiar fichero a la máquina remota
    - name: "Copiar fichero foo.conf a la máquina remota"
      copy:
        src: files/foo.conf
        dest: /etc
        owner: debian
        group: debian
        mode: '0644'

    # Copiar un template a un fichero
    - name: "Copiar un template a /var/www/html/index.html"
      template: 
        src: template/index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
